version: '3'
services:
  max-milhas-postgres-test:
    image: postgres:13-alpine
    container_name: max-milhas-postgres-test
    restart: always
    env_file:
      - .env.test
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-test:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}

  max-milhas-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: max-milhas-test
    depends_on:
      - max-milhas-postgres-test
    env_file:
      - .env.test
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    working_dir: /usr/src/
    command: bash -c "npx prisma generate && npx prisma migrate dev && npm run test"

volumes:
  postgres-test:
